name = "pb"
compatibility_date = "2023-01-28"

account_id = "tingyuns007"
workers_dev = false
main = "src/index.js"

# config for default production environment
vars = { ENVIRONMENT = "production" }
route = { pattern = "shz.al", custom_domain = true }
kv_namespaces = [
  { binding = "PB", id = "tingyuns007" },
]
